# version: '3'
# services:
#   app:
#     build: ./backend
#     restart: unless-stopped
#     depends_on:
#       - db
#     networks:
#       - backnet
#     volumes:
#       - ./backend:/orders_management_app
#     ports:
#       - "8000:5000"
#     environment:
#       MYSQL_HOST: db
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 12345678
#       MYSQL_DB: orders_management

#   db:
#     build: ./db/
#     command: '--default-authentication-plugin=mysql_native_password'
#     restart: always
#     volumes:
#       - app-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: 12345678
#       MYSQL_DATABASE: orders_management

#     ports:
#       - "32001:3306"

#     expose:
#       - 3306
#       - 32001

#     networks:
#       - backnet

# volumes:
#   app-data:

# networks:
#   backnet:

version: '3'
services:
  srv:
    image: orders_srv
    container_name: srv
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
    - "8000:5000"

  db:
    # image: mysql_db
    # image: mysql:8.0
    container_name: db
    restart: unless-stopped
    build:
      context: ./db
    volumes:
    # - ./db/scripts/schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    - orders-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: orders_management

    ports:
    - "33021:3306"

volumes:
  orders-data:
    driver: local